language: python
sudo: false
cache: pip

python:
  - "2.7"


addons:

  postgresql: "9.6"

env:

  global:
  - VERSION="10.0" LINT_CHECK="0"  UNIT_TEST="1"
  - VERSION="10.0" ODOO_REPO="odoo/odoo" LINT_CHECK="0"
  - VERSION="10.0" ODOO_REPO="OCA/OCB" LINT_CHECK="0"

  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="odoo/odoo" MAKEPOT="1" UNIT_TEST="1"
  - TESTS="1" ODOO_REPO="OCA/OCB" UNIT_TEST="1"



install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly


script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
