language: python
python:

  - "2.7"

# command to install dependencies
install:

  sudo yum install -y postgresql-server
  sudo postgresql-setup initdb
  sudo systemctl enable postgresql
  sudo systemctl start postgresql
  sudo yum install yum-utils
  sudo yum-config-manager --add-repo=https://nightly.odoo.com/10.0/nightly/rpm/odoo.repo
  sudo yum install -y odoo
  sudo npm install -g less


  wget -O - https://nightly.odoo.com/odoo.key | apt-key add -
  echo "deb http://nightly.odoo.com/10.0/nightly/deb/ ./" >> /etc/apt/sources.list.d/odoo.list
  apt-get update && apt-get install odoo
  - pip install -r requirements.txt
  sudo service odoo restart
  sudo systemctl enable odoo
  sudo systemctl start odoo
# command to run tests

script:
  - addons/tests
